version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.7.10"
      FORGEVERSION: "10.13.4.1614"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mine:/data
